version: '3'

services:
  api:
    image: gmails:step
    build: ./api
    ports:
      - "5000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis
