version: '3'

services:
  api:
    image: gmails:step
    build: ./api
    ports:
      - "5000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./finaldata.csv:/shared_data/finaldata.csv

  listadoestudiantes:
    build:
      context: ./listadoestudiantes
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:8000  # Cambiado a 8000 para reflejar el puerto del contenedor de la API

  redis:
    image: redis
